"""Rebuild vc_brain.db deterministically for the demo (spec: demo determinism).

Backs up the existing DB, then: scan (replay) -> velocity (replay) -> founder-score
backfill -> screening (top thesis-matched founders + the 3 fixtures, both theses)
-> diligence on the 3 fixtures (thesis A; Corevance also under thesis B for the
thesis-swap beat) -> eval summary to docs/EVAL.md.

LLM/HTTP calls hit the replay cache; anything unseeded runs live once (needs a key)
and is cached for every run after. Run twice: second run must be byte-stable.
"""
import os
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import config, instrument  # noqa: E402
from app.memory import db, founder_score, ingest  # noqa: E402
from app.screening import axes as axes_mod  # noqa: E402
from app.screening import thesis as thesis_mod  # noqa: E402
from app.sources import scanner, velocity  # noqa: E402

REPLAY_FALLBACK_LIVE = False  # replay first; set env keys and this stays False
THESIS_A = "config/thesis_preseed_ai_infra.yaml"
THESIS_B = "config/thesis_alt.yaml"
FIXTURES = ["founder_a_tracewell", "founder_b_corevance", "founder_c_parcelmind"]
N_SCREEN = 8  # top thesis-matched outbound founders to screen


def main() -> None:
    t0 = time.time()
    if os.environ.get("DATABASE_URL"):
        raise SystemExit("rebuild_demo rebuilds the LOCAL SQLite demo DB — unset "
                         "DATABASE_URL (deployed Postgres is seeded via app/seed.py)")
    if config.DB_PATH.exists():
        bak = config.DB_PATH.with_suffix(".db.bak")
        shutil.move(config.DB_PATH, bak)
        print(f"[backup] moved old DB to {bak.name}")
    conn = db.connect()
    db.init_db(conn)
    now = datetime.now(timezone.utc).isoformat()

    # 1. Outbound scan from the replay cache.
    ta = thesis_mod.load_thesis(THESIS_A)
    res = scanner.run_scan(conn, scanner.topics_for(ta), replay=True)
    print(f"[scan] counts={res['counts']} resolved={res['resolved']} "
          f"dropped={len(res['dropped'])}")

    # 2. Velocity (replay) + founder-score history for every resolved founder.
    fids = [r["fid"] for r in conn.execute(
        "SELECT DISTINCT founder_id fid FROM resolutions").fetchall()]
    vel = 0
    for fid in fids:
        try:
            if velocity.fetch(conn, fid, replay=True):
                vel += 1
        except Exception:
            pass  # no cached commits for this repo — velocity stays unassessed
    for fid in fids:
        founder_score.recompute(conn, fid, "scan", now=now)
    print(f"[velocity] {vel} founders with cadence · [score] {len(fids)} backfilled")

    # 3. Screening: top thesis-matched outbound founders under both theses.
    rows = conn.execute(
        "SELECT r.founder_id fid, GROUP_CONCAT(s.content,'\n') blob, COUNT(*) n "
        "FROM resolutions r JOIN signals s ON s.id=r.signal_id "
        "GROUP BY r.founder_id").fetchall()
    ranked = sorted(rows, key=lambda r: (
        sum(1 for t in ta.topics if t in (r["blob"] or "").lower()), r["n"]),
        reverse=True)[:N_SCREEN]
    tb = thesis_mod.load_thesis(THESIS_B)
    for th in (ta, tb):
        for r in ranked:
            out = axes_mod.screen(conn, r["fid"], th, replay=False)
            tag = f"KILLED: {out['kill_reason']}" if out["killed"] else \
                " ".join(f"{k}={a['score']}" for k, a in out["axes"].items())
            print(f"[screen·{th.name[:12]}] {r['fid']}: {tag}")

    # 4. Diligence on the three fixtures (screen them too, so axes render).
    from app.diligence import loader, pipeline
    for fx in FIXTURES:
        fid = loader.load_fixture(conn, fx, replay=True)
        with instrument.stage(conn, fid, "screen"):
            axes_mod.screen(conn, fid, ta, replay=False)
        axes_mod.screen(conn, fid, tb, replay=False)  # thesis-swap beat
        r = pipeline.run_diligence(conn, fid, ta, replay=False)
        print(f"[diligence·A] {fid}: {r['recommendation'].decision} "
              f"claims={r['claims']} validator_ok={r['violations'].ok}")
    # Thesis-swap beat: Corevance under the low-risk Series-A lens.
    fid = loader.load_fixture(conn, "founder_b_corevance", replay=True)
    r = pipeline.run_diligence(conn, fid, tb, replay=False)
    print(f"[diligence·B] {fid}: {r['recommendation'].decision}")

    write_eval(conn)
    print(f"[done] rebuilt in {time.time() - t0:.1f}s -> {config.DB_PATH.name}")


def write_eval(conn) -> None:
    """Eval numbers for the write-up (spec §7-lite) — computed, never asserted."""
    lines = ["# Eval summary (generated by scripts/rebuild_demo.py)", ""]
    tiers = conn.execute(
        "SELECT corroboration, COUNT(*) n, ROUND(AVG(trust),2) avg_trust FROM claims "
        "GROUP BY corroboration ORDER BY n DESC").fetchall()
    lines += ["## Claims by corroboration tier", "",
              "| tier | claims | avg trust |", "|---|---|---|"]
    lines += [f"| {t['corroboration']} | {t['n']} | {t['avg_trust']} |" for t in tiers]
    decs = conn.execute("SELECT founder_id, thesis, decision FROM memos").fetchall()
    lines += ["", "## Decisions", ""]
    lines += [f"- {d['founder_id']} · {d['thesis']}: **{d['decision']}**" for d in decs]
    lines += ["", "## Latency (signal -> decision, per diligence founder)", ""]
    for d in decs:
        lat = instrument.latency_strip(conn, d["founder_id"])
        if lat["stages"]:
            strip = " → ".join(f"{s} {sec:.1f}s" for s, sec in lat["stages"])
            lines.append(f"- {d['founder_id']}: {strip} = {lat['total_seconds']:.1f}s")
    stats = {
        "founders": conn.execute("SELECT COUNT(*) c FROM founders").fetchone()["c"],
        "signals": conn.execute("SELECT COUNT(*) c FROM signals").fetchone()["c"],
        "resolved": conn.execute("SELECT COUNT(*) c FROM resolutions").fetchone()["c"],
        "droplog": conn.execute(
            "SELECT COUNT(DISTINCT signal_id) c FROM droplog").fetchone()["c"],
        "adjudications": conn.execute(
            "SELECT COUNT(*) c FROM adjudications").fetchone()["c"],
        "kills": conn.execute(
            "SELECT COUNT(DISTINCT founder_id) c FROM kill_log").fetchone()["c"],
    }
    lines += ["", "## Memory", ""]
    lines += [f"- {k}: {v}" for k, v in stats.items()]
    path = config.ROOT / "docs" / "EVAL.md"
    path.write_text("\n".join(lines) + "\n")
    print(f"[eval] wrote {path.relative_to(config.ROOT)}")


if __name__ == "__main__":
    main()
